[package]
name = "archero"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19.1", features = ["bevy_dev_tools"] }
bevy_widget = { path = "../bevy_widget" }
leafwing-input-manager = "0.21.0"

# config
serde = { version = "1.0.229", features = ["derive"] }
ron = { version = "0.12.2" }

bevy_asset_loader = "0.27.0"
bevy_common_assets = { version = "0.17.0", features = ["ron"] }

[profile.dev.package.parley]
debug-assertions = false

[profile.dev.package.icu_provider]
debug-assertions = false

[features]
debug = ["bevy/debug"]